apiVersion: v1
kind: Service
metadata:
  name: restromaster-frontend-service
spec:
  selector: 
      app: restromaster-frontend
  ports: 
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: restromaster-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: restromaster-frontend
  template: 
    metadata: 
      labels: 
        app: restromaster-frontend
    spec: 
      containers:
        - name: restromaster-frontend
          image: narualay030/restromaster-frontend
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 10