apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  selector: 
      app: postgres-db
  ports: 
    - protocol: 'TCP'
      port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posgres-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: postgres-db
  template: 
    metadata: 
      labels: 
        app: postgres-db
    spec: 
      containers:
        - name: postgres-db
          image: postgres
          env: 
            - name: POSTGRES_PASSWORD
              value: password